This is a collection of notional testdata for 
proc and m4.  Due to size constraints, large 
testdata will be hosted outside of this repo.

* Developer Notes
testdata*.xlsx is a canonical m4 project input file.
Future versions will have tsv-based, .gz, and binary 
inputs.  For now, we conform to the legacy implementation (xlsx).

It should be robust enough to serve as a commensurate stress 
test for both m4 and proc.

** proc-specific data
If you want to have a re-usable dataset for proc testing, we have
a big and a small set of runs derived from the testdata.

1.  [[https://s3-us-gov-west-1.amazonaws.com/marathon/AUDIT_small.zip ] Small ~(1mb/10mb) dataset] 
2.  [[https://s3-us-gov-west-1.amazonaws.com/marathon/AUDIT_big.zip] Large ~(50mb/500mb?) dataset]

Upon extraction, you should be able to run proc.example/run-sample! on either root folder, since they
contain the canonical audit trail files from a run.

** interests
interests.clj is included to provide a basis for rendering or processing the notional data using proc.

* License

Copyright fs-tom 2012-2017

Spoon's Operations Research Kit and encompassing libraries are licensed under the 
Eclipse Public License v 1.0.

Segments of inline open source code that have both license and attributions 
provided for the gracious authors.  Please contact me via github if I missed someone and 
need to issue a correction.



 

 

